Update tsc `lib` to fix a failing test
  test/group.test.ts:69:22 - error TS2339: Property 'groups' does not exist on type 'RegExpExecArray'.

  69       expect(matches.groups).toEqual({

Additionally, this commit will:

- Change the build target to ES3. I was earlier under the misconception
that the target had to be the latest version whose features we use.
- Remove support for node 9 because it doesn't support named capturing
groups.