Fix error TS2339
FAIL  test/examples.test.ts

● Test suite failed to run

  TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):

  src/any-character-but.ts:8:40 - error TS2339: Property 'entries'
  does not exist on type 'ObjectConstructor'.

  8   for (const [i, expression] of Object.entries(characters)) {